name: PR
on: [pull_request, workflow_call]
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: nm

      - name: Install dependencies
        run: npm ci

  commitlint:
    needs: setup
    name: Commitlint
    uses: ./.github/workflows/commitlint.yml

  lint:
    needs: setup
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: nm

      - name: Run `lint:check` npm script
        run: npm run lint-check

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: nm

      - name: Run unit tests
        run: npm run test-ci

  e2e-tests:
    needs: setup
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: nm

      - name: Install playwright
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npm run e2e-ci

        if: always()
      - uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
