name: Release

on:
  push:
    tags:
      - 'v\d+'

jobs:
  tests:
    uses: ./.github/workflows/pr.yml

  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get information
        id: tags
        run: |
          currentTag=${{ github.ref_name }}
          previousTag=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "currentTag=${currentTag}" >> $GITHUB_OUTPUT
          echo "previousTag=${previousTag}" >> $GITHUB_OUTPUT
          echo "author=${{ github.actor }}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%d.%m.%Y %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Build Changelog
        id: build_changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            fix: Bug Fixes
            build: Build System & Dependencies
            feat: New Features
            ci: CI
            docs: Documentation
            test: Tests
            perf: Performance Improvements
            refactor: Refactors
            chore: Chores
            style: Code Style
            revert: Reverts
          default-commit-type: Other Changes
          mention-authors: true
          mention-new-contributors: true
          include-compare-link: true
          include-pr-links: true
          include-commit-links: true
          semver: false
          use-github-autolink: true

      - name: Create release issue
        id: create_issue
        uses: JasonEtco/create-an-issue@v2
        env:
          VERSION: ${{ steps.tags.outputs.currentTag}}
          AUTHOR: ${{ steps.tags.outputs.author }}
          DATE: ${{ steps.tags.outputs.date }}
          CHANGELOG: ${{ steps.build_changelog.outputs.changelog }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/TEMPLATE.md
          update_existing: true
          search_existing: all

      - name: Add comment with test results to issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.create_issue.outputs.number }}
          body: |
            ## Tests results
            Download test results:
            ${{github.server_url}}/${{ github.repository }}/actions/runs/${{github.run_id}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      issueNumber: ${{ steps.create_issue.outputs.number }}

  build-and-deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install correct Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build

      - name: Comment issue with GH Pages
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ needs.release.outputs.issueNumber }}
          body: |
            ## Deploy
            https://syrym-umbetov.github.io/yandex-infrastructure/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ needs.release.outputs.issueNumber }}
          comment: |
            Issue automatically closed by successful deployment
